flash-tarball: fix settings restore with preexisting backup
(cherry picked from commit 2b8aea16334fa58d547f29dc61db5447d3fdabf3)

diff --git a/flash-tarball b/flash-tarball
--- a/flash-tarball
+++ b/flash-tarball
@@ -47,8 +47,13 @@ if ! is_chardev "${UBI_DEVICE}" && ! attach_ubi_device "${MTD_DEVICE}"; then
 	attach_ubi_device "${MTD_DEVICE}" || abort "Failed to attach ${MTD_DEVICE} to UBI"
 fi
 
+[ ! -f "${RECOVERY_CACHE}/settings.tar.gz" ] || cp ${RECOVERY_CACHE}/settings.tar.gz ${SETTINGS}
 if is_chardev "${ROOT_PARTITION}"; then
 	${BACKUP_SETTINGS}
+fi
+[ "${RESTORE_SETTINGS}" = ":" -o -f "${SETTINGS}" ] || abort "Can't restore settings without prior backup!"
+
+if is_chardev "${ROOT_PARTITION}"; then
 	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
 	remove_ubi_volume || abort "Failed to remove UBI volume"
 fi
@@ -61,7 +66,7 @@ run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "F
 ${RESTORE_SETTINGS}
 unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
 
-update_cache "${SETTINGS}"
+[ "${BACKUP_SETTINGS}" = ":" ] || update_cache "${SETTINGS}"
 unmount_cache
 
 info "Finished successfully. You may reboot now."
