recovery: fix settings restore with preexisting backup
(cherry picked from commit 063461c06264ea9e7123c98fcfd81cacf8d3d2bd)

diff --git a/recovery b/recovery
--- a/recovery
+++ b/recovery
@@ -471,9 +471,11 @@ EOF
 mount_cache
 fetch_signed "${BASE_URI}" "${FILENAME}"
 
+[ ! -f "${RECOVERY_CACHE}/settings.tar.gz" ] || cp ${RECOVERY_CACHE}/settings.tar.gz ${SETTINGS}
 if blkdev_has_filesystem "${ROOT_PARTITION}"; then
 	${BACKUP_SETTINGS}
 fi
+[ "${RESTORE_SETTINGS}" = ":" -o -f "${SETTINGS}" ] || abort "Can't restore settings without prior backup!"
 
 if ! is_blockdev "${ROOT_PARTITION}" || ! blkdev_has_filesystem "${DATA_PARTITION}"; then
 	unmount "${ROOT_MOUNTPOINT}" || abort "Failed to unmount root filesystem"
@@ -495,7 +497,7 @@ run_postinsts "${ROOT_MOUNTPOINT}" dreambox-secondstage kernel-image || abort "F
 ${RESTORE_SETTINGS}
 unmount "${ROOT_MOUNTPOINT}" || warn "Failed to unmount root filesystem"
 
-update_cache "${SETTINGS}"
+[ "${BACKUP_SETTINGS}" = ":" ] || update_cache "${SETTINGS}"
 update_cache_signed "${FILENAME}"
 unmount_cache
 
